blank_issues_enabled: true
contact_links:
  - name: Usage Questions (Slack)
    url: https://cloud-native.slack.com/archives/C09SPL5G3MY
    about: Please ask questions about configuration and usage in the keycloak-config-cli Slack space.
