{{ if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak-config-cli.fullname" . }}
  labels:
  {{- include "keycloak-config-cli.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.secrets }}
    {{ $name }}: "{{ tpl $value $ | b64enc }}"
  {{- end }}
  {{- end }}
