name: CI and Deployments

on:
  push:
    branches:
      - feat/documentation
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feat/documentation'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install mkdocs-material[imaging]
      - name: Build and Deploy Documentation
        run: mkdocs gh-deploy --force

  publish-chart:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: contrib/charts
          charts_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts
          branch: gh-pages
          target_dir: helm-charts
          linting: off